# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdcf3703c36372fb907ef3a429e6e018f53fcecf8fd8c52feaa64a5aa41aaf1b7dddfc26169297befcc397278a2a0add7651d9fb4879a0d4b8869371d6c2e052

test:
  secret_key_base: 5746964024fae11a084ecb2c01e600e7e829d8164eee3d8a63d5d0b6ffcb6e228229744b3e960366a106e2d8d21701c698c1b182671139a4f2545a2535dd9126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
